Final NavBar
WildCodeSchool-2024-09/JS-Paris-P2-LesPerses pull request #13
Opened 2024-11-22 09:34 UTC by Karim-BH

accepte ! il n'y a que du CSS tkt ;)

2024-11-22 10:10 UTC, BryanDev1 approved these changes

2024-11-22 11:07 UTC, mickaellambert requested changes

2024-11-22 11:07 UTC, mickaellambert commented on src/App.css
> +  1. Use a more-intuitive box-sizing model.
Créer un fichier à part pour le reset et penser à enlever les commentiares générés par ChatGPT

2024-11-22 13:57 UTC, BryanDev1 commented on src/App.css
> +  1. Use a more-intuitive box-sizing model.
le reset va etre fait et les commentaire vont etre enlevé

2024-11-25 08:43 UTC, mickaellambert requested changes

2024-11-25 08:43 UTC, mickaellambert commented on src/components/NavBar/NavBar.tsx
Penser a supprimer les commentaires inutiles

2024-11-25 08:43 UTC, mickaellambert commented on src/components/NavBar/NavBar.css
Penser a supprimer les commentaires inutiles

2024-11-25 08:57 UTC, Karim-BH commented on src/components/NavBar/NavBar.tsx
c'est fait

2024-11-25 13:43 UTC, merged