Home quiz
WildCodeSchool-2024-09/JS-Paris-P2-LesPerses pull request #6
Opened 2024-11-19 10:24 UTC by Karim-BH

2024-11-19 10:28 UTC, MarinaMassot approved these changes

2024-11-19 14:24 UTC, mickaellambert requested changes

2024-11-19 14:24 UTC, mickaellambert commented on src/components/NavBar.tsx
> +import React from "react";
Je comprends pas trop l'utilisé de ce fichier

2024-11-19 14:24 UTC, mickaellambert commented on src/App.tsx
> +			<Header />
La PR concerne le quizz en lui même ou le header ?

2024-11-19 14:24 UTC, mickaellambert commented on src/components/Themedif.tsx
> +	data,
Le naming ici est pas fou, à quoi correspond data ?

2024-11-19 14:24 UTC, mickaellambert commented on src/components/quiz-components/EndQuiz.tsx
> +			<p className="result">Ton score : <strong>20</strong> sur 399 et ton pourcentage de réussite est de (20)% </p>
Le score n'est pas censé être dynamique ? Tout le monde aura 20 sur 399 ? Haha

2024-11-19 14:24 UTC, mickaellambert commented on src/components/quiz-components/Header.tsx
> +				<QuizMain />
Le quizz va dans le header ?

2024-11-19 14:24 UTC, mickaellambert commented on src/components/quiz-components/Loading.tsx
> +<div className="loader-container">
Ici, l'indentation est bizarre

2024-11-19 14:24 UTC, mickaellambert commented on src/components/quiz-components/NextButton.tsx
> +		<button type="button" className="next" onClick={handleQuestionsClick}>
Pareil, le naming est pas fou, plutôt que `handleQuestionsClick` pourquoi pas `nextQuestion` ?

2024-11-19 14:24 UTC, mickaellambert commented on src/components/quiz-components/Options.tsx
> +//badAnswers = API badAnswers
Attention à ne pas laisser les commentaires inutiles lors de la PR

2024-11-19 14:24 UTC, mickaellambert commented on src/components/quiz-components/QuizMain.tsx
> +			{/* <section className="quiz">
Ce composant est vide du coup ?

2024-11-19 14:24 UTC, mickaellambert commented on src/components/quiz-components/Questions.tsx
> +	useEffect(() => {
Je comprends pas trop à quoi sert ce useEffect, il permet d'initialiser quelque chose ?

2024-11-19 14:24 UTC, mickaellambert commented on src/components/quiz-components/Timer.tsx
> +	return <span className="timer">Time: 00:20</span>;
Le temps sera toujours à 20 secondes ?

2024-11-19 14:24 UTC, mickaellambert commented on src/components/quiz-components/Validate.tsx
> +export default function Validate({
Peut être le renommer en "CheckAnswer", "Validate" c'est un peu vague

2024-11-19 14:24 UTC, mickaellambert commented on src/components/quiz-components/Validate.tsx
> +			const isValid = selectedAnswer === correctAnswer;
Pas besoin de créer une variable ici, autant faire directement : `onValidate(selectedAnswer === correctAnswer);`

2024-11-21 09:42 UTC, BryanDev1 commented on src/App.tsx
> +			<Header />
la PR concerne le quizz en lui même

2024-11-21 09:44 UTC, BryanDev1 commented on src/components/quiz-components/EndQuiz.tsx
> +			<p className="result">Ton score : <strong>20</strong> sur 399 et ton pourcentage de réussite est de (20)% </p>
Oui composant inutile ici

2024-11-21 09:44 UTC, BryanDev1 commented on src/components/quiz-components/Loading.tsx
> +<div className="loader-container">
component supprimé

2024-11-21 09:45 UTC, BryanDev1 commented on src/components/quiz-components/QuizMain.tsx
> +			{/* <section className="quiz">
on en aura besoin ultérieurement

2024-11-21 10:16 UTC, mickaellambert approved these changes

2024-11-21 10:16 UTC, merged